import Head from "next/head";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<div className="container">
					<p className="font-bold text-3xl">Lorem!</p>

					<p>
						Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam
						blanditiis fugit eos obcaecati, reprehenderit itaque dolorum totam
						dolores non fuga iusto sunt aperiam saepe necessitatibus eligendi.
						Repudiandae ex tempora blanditiis!
					</p>
				</div>
			</main>
		</>
	);
}
